import React, { createContext, useState, useContext } from 'react';

// Translations
const translations = {
  en: {
    // Navigation
    home: 'Home',
    products: 'Products',
    about: 'About Us',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    cart: 'Cart',
    myOrders: 'My Orders',
    myProfile: 'My Profile',
    
    // Hero Section
    heroTitle: 'PANJ',
    heroSubtitle: 'Discover timeless beauty with our handcrafted luxury jewelry collection',
    heroButton: 'Explore Collection',
    
    // Products
    newCollection: 'New Collection',
    newCollectionDesc: 'Latest unique designs crafted with artistry and passion',
    hotTrends: 'Hot Trends',
    hotTrendsDesc: 'Most loved and chosen jewelry pieces by our customers',
    viewDetails: 'View Details',
    hotTrend: '🔥 Hot Trend',
    luxuryJewelry: 'Luxury jewelry from PANJ',
    bestSeller: 'Best seller product',
    noNewProducts: 'No new products available',
    noHotProducts: 'No hot products available',
    
    // Products Page
    allProducts: 'All Products',
    productsInCategory: 'Products in category',
    noProductsFound: 'No products found',
    noProductsInCategory: 'No products found in this category',
    sortBy: 'Sort by',
    sortByName: 'Name',
    sortByPrice: 'Price',
    sortByNewest: 'Newest',
    sortByPopular: 'Popular',
    priceRange: 'Price Range',
    allPrices: 'All Prices',
    filterBy: 'Filter by',
    category: 'Category',
    color: 'Color',
    material: 'Material',
    clearFilters: 'Clear Filters',
    showingResults: 'Showing',
    of: 'of',
    results: 'results',
    
    // About Page
    aboutUs: 'About Us',
    aboutPanj: 'About PANJ',
    aboutTitle: 'Crafting Timeless Beauty Since 2020',
    aboutDescription: 'PANJ is Vietnam\'s premier luxury jewelry brand, dedicated to creating exquisite pieces that tell your unique story. Our master craftsmen combine traditional techniques with contemporary design to create jewelry that transcends time.',
    ourStory: 'Our Story',
    ourStoryText: 'Founded with a passion for exceptional craftsmanship, PANJ has become synonymous with luxury and elegance. Each piece in our collection is meticulously handcrafted using the finest materials sourced from around the world.',
    ourMission: 'Our Mission',
    ourMissionText: 'To bring you jewelry that celebrates life\'s most precious moments. We believe that every piece should be as unique as the person wearing it.',
    ourVision: 'Our Vision',
    ourVisionText: 'To be the world\'s most trusted and admired luxury jewelry brand, known for our commitment to quality, craftsmanship, and customer satisfaction.',
    
    // Contact Page
    contactUs: 'Contact Us',
    getInTouch: 'Get in Touch',
    contactDescription: 'We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    subject: 'Subject',
    message: 'Message',
    sendMessage: 'Send Message',
    sending: 'Sending...',
    messageSent: 'Message sent successfully!',
    messageError: 'Error sending message. Please try again.',
    contactInfo: 'Contact Information',
    address: 'Address',
    openingHours: 'Opening Hours',
    mondayToFriday: 'Monday - Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    closed: 'Closed',
    owner: 'Owner',
    linkedinProfile: 'View LinkedIn Profile',
    businessHours: 'Business Hours',
    daily: 'Daily',
    fullName: 'Full Name',
    enterName: 'Enter your name',
    formDescription: 'Please fill out the form below and we\'ll get back to you as soon as possible.',
    contactSubtitle: 'Get in touch with us - we\'d love to hear from you',
    
    // Social Login
    continueWithGoogle: 'Continue with Google',
    continueWithFacebook: 'Continue with Facebook',
    signUpWithGoogle: 'Sign up with Google',
    signUpWithFacebook: 'Sign up with Facebook',
    socialLoginError: 'Social login failed. Please try again.',
    
    // Features
    whyChoosePanj: 'Why Choose PANJ',
    whyChoosePanjDesc: 'We are committed to bringing you the best experiences',
    qualityTitle: 'Superior Quality',
    qualityDesc: 'Products crafted from the finest materials worldwide with international standards',
    designTitle: 'Exclusive Design',
    designDesc: 'Each piece of jewelry carries its own story and unique non-duplicated design',
    serviceTitle: 'Perfect Service',
    serviceDesc: 'Lifetime warranty, free shipping and 24/7 customer care service',
    
    // Authentication
    loginSubtitle: 'Sign in to your PANJ account',
    username: 'Username',
    password: 'Password',
    usernamePlaceholder: 'Enter your username',
    passwordPlaceholder: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    loggingIn: 'Signing in...',
    or: 'or',
    continueWithGoogle: 'Continue with Google',
    continueWithFacebook: 'Continue with Facebook',
    noAccount: "Don't have an account?",
    signUp: 'Sign up',
    pleaseInputCredentials: 'Please enter your username and password',
    loginFailed: 'Login failed',
    loginError: 'An error occurred during login',
    incorrectCredentials: 'Incorrect username or password. Please check your credentials and try again.',
    accountDeactivated: 'Your account is not activated. Please check your email to activate your account.',
    
    // Sign Up
    createAccount: 'Create Account',
    signupSubtitle: 'Join PANJ and discover luxury jewelry',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    confirmPassword: 'Confirm Password',
    fullNamePlaceholder: 'Enter your full name',
    emailPlaceholder: 'Enter your email address',
    phonePlaceholder: 'Enter your phone number',
    confirmPasswordPlaceholder: 'Confirm your password',
    agreeToTerms: 'I agree to the',
    termsAndConditions: 'Terms and Conditions',
    subscribeNewsletter: 'Subscribe to newsletter for exclusive offers',
    creatingAccount: 'Creating account...',
    signUpWithGoogle: 'Sign up with Google',
    signUpWithFacebook: 'Sign up with Facebook',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign in',
    passwordMismatch: 'Passwords do not match',
    mustAgreeToTerms: 'You must agree to the terms and conditions',
    signupSuccess: 'Account created successfully! Please check your email to activate your account.',
    signupFailed: 'Account creation failed',
    signupError: 'An error occurred during account creation',
    activationSent: 'Activation email sent successfully',
    usernameExists: 'Username already exists',
    emailExists: 'Email already exists',
    
    // Account Activation
    accountActivation: 'Account Activation',
    activatingAccount: 'Activating your account...',
    activationSuccess: 'Your account has been successfully activated!',
    activationFailed: 'Account activation failed',
    activationError: 'An error occurred during activation',
    redirectingToLogin: 'Redirecting to login page...',
    activationExpired: 'Activation link has expired',
    alreadyActivated: 'Account is already activated',
    emailConfirmationMessage: 'Please check your email and click the activation link to confirm your account before logging in.',
    goToLogin: 'Go to Login',
    signUpAgain: 'Sign Up Again',
    
    // Notifications
    success: 'Success',
    error: 'Error', 
    warning: 'Warning',
    info: 'Information',
    networkError: 'Network Error',
    checkConnection: 'Please check your internet connection and try again',
    
    // Footer
    footerDesc: 'Leading luxury jewelry brand in Vietnam. We create exquisite jewelry pieces, bringing timeless beauty to women.',
    productsMenu: 'Products',
    allProducts: 'All Products',
    rings: 'Rings',
    necklaces: 'Necklaces',
    bracelets: 'Bracelets',
    earrings: 'Earrings',
    customerSupport: 'Customer Support',
    contactUs: 'Contact Us',
    shipping: 'Shipping',
    returns: 'Returns',
    warranty: 'Warranty',
    careGuide: 'Care Guide',
    contactInfo: 'Contact',
    address: '📍 Binh Thanh, Ho Chi Minh City',
    contactEmail: '✉️ truonghoanglong1802@gmail.com',
    linkedin: '💼 LinkedIn Profile',
    hours: '🕒 8:00 - 22:00 (Daily)',
    copyright: '© 2025 PANJ Jewelry. All rights reserved.',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    sitemap: 'Sitemap',
    
    // Currency
    currency: 'USD',
    
    // Common
    loading: 'Loading...',
    search: 'Search products...',
    welcome: 'Welcome',
    
    // Product Detail Page
    reviews: 'Reviews',
    taxIncluded: 'Tax included',
    freeShipping: 'Free shipping',
    size: 'Size',
    sizeGuide: 'Size Guide',
    quantity: 'Quantity',
    adding: 'Adding...',
    addToCart: 'Add to Cart',
    addToWishlist: 'Add to Wishlist',
    addedToCart: 'Added to cart successfully!',
    pleaseSelectSizeAndColor: 'Please select size and color',
    authenticGuarantee: 'Authentic Guarantee',
    freeShippingOver: 'Free shipping over $100',
    returnPolicy: '30-day return policy',
    lifetimeWarranty: 'Lifetime warranty',
    share: 'Share',
    needHelp: 'Need Help?',
    description: 'Description',
    specifications: 'Specifications',
    careInstructions: 'Care Instructions',
    productDescription: 'Product Description',
    luxuryJewelryDescription: 'Exquisite craftsmanship meets timeless elegance. This stunning piece is meticulously handcrafted using the finest materials, ensuring both beauty and durability. Perfect for special occasions or everyday luxury.',
    handcraftedExcellence: 'Handcrafted with excellence',
    premiumMaterials: 'Premium materials only',
    timelessDesign: 'Timeless design',
    perfectGift: 'Perfect for gifting',
    material: 'Material',
    plating: 'Plating',
    stones: 'Stones',
    weight: 'Weight',
    dimensions: 'Dimensions',
    origin: 'Origin',
    cleaning: 'Cleaning',
    storage: 'Storage',
    avoid: 'Avoid',
    cleaningInstructions: 'Clean gently with a soft cloth and mild soap. Rinse with clean water and dry thoroughly.',
    storageInstructions: 'Store in original box or soft pouch to prevent scratches and tarnishing.',
    avoidInstructions: 'Avoid contact with perfumes, lotions, and harsh chemicals.',
    addedToCart: 'Product added to cart successfully!',
    close: 'Close',
    
    // Cart Page
    emptyCart: 'Your Cart is Empty',
    emptyCartMessage: 'Looks like you haven\'t added anything to your cart yet.',
    continueShopping: 'Continue Shopping',
    itemsInCart: 'Items in Cart',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    tax: 'Tax',
    total: 'Total',
    free: 'Free',
    proceedToCheckout: 'Proceed to Checkout',
    
    // Payment
    payment: 'Payment',
    paymentDetails: 'Payment Details',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    cardholderName: 'Cardholder Name',
    payNow: 'Pay Now',
    processing: 'Processing...',
    backToCart: 'Back to Cart',
    testPayment: 'Test Payment',
    securePayment: 'Secure Payment',
    testMode: 'Test Mode',
    enterCardNumber: 'Enter your card number',
    enterExpiryDate: 'MM/YY',
    enterCvv: 'CVV',
    enterCardholderName: 'Enter cardholder name',
    paymentSuccessful: 'Payment Successful!',
    paymentFailed: 'Payment Failed',
    orderPlaced: 'Your order has been placed successfully. Thank you for your purchase!',
    orderTotal: 'Order Total',
    paymentMethod: 'Payment Method',
    status: 'Status',
    confirmed: 'Confirmed',
    creditCard: 'Credit Card',
    redirectingHome: 'Redirecting to home page...',
    tryAgain: 'Try Again',
    backToCart: 'Back to Cart',
    
    // Payment Process
    shippingInfo: 'Shipping Information',
    shippingInfoDesc: 'Please provide your shipping address and delivery preferences',
    paymentInfo: 'Payment Information',
    orderConfirmation: 'Order Confirmation',
    recipientName: 'Recipient Name',
    recipientPhone: 'Recipient Phone',
    streetAddress: 'Street Address',
    ward: 'Ward',
    district: 'District',
    city: 'City',
    country: 'Country',
    postalCode: 'Postal Code',
    deliveryMethod: 'Delivery Method',
    standard: 'Standard',
    express: 'Express',
    orderNotes: 'Order Notes',
    orderNotesPlaceholder: 'Any special instructions for your order...',
    optional: 'Optional',
    next: 'Next',
    useCustomerAddress: 'Use Customer Address',
    edit: 'Edit',
    editAddress: 'Edit Address',
    recipientInfo: 'Recipient Information',
    addressDetails: 'Address Details',
    deliveryOptions: 'Delivery Options',
    additionalInfo: 'Additional Information',
    standardDeliveryDesc: '5-7 business days delivery',
    expressDeliveryDesc: '2-3 business days delivery',
    
    // My Orders
    myOrders: 'My Orders',
    orderHistory: 'Order History',
    orderId: 'Order ID',
    orderDate: 'Order Date',
    viewDetails: 'View Details',
    orderDetails: 'Order Details',
    product: 'Product',
    quantity: 'Quantity',
    amount: 'Amount',
    subtotal: 'Subtotal',
    noOrders: 'No Orders Found',
    noOrdersMessage: 'You haven\'t placed any orders yet. Start shopping to see your orders here!',
    continueShopping: 'Continue Shopping',
    backToOrders: 'Back to Orders',
    orderSummary: 'Order Summary',
    
    // My Profile
    myProfile: 'My Profile',
    personalInformation: 'Personal Information',
    updateProfile: 'Update Profile',
    updating: 'Updating...',
    profileUpdated: 'Profile updated successfully!',
    profileUpdateError: 'Failed to update profile',
    enterUsername: 'Enter your username',
    enterPassword: 'Enter your password',
    enterName: 'Enter your full name',
    enterPhone: 'Enter your phone number',
    enterEmail: 'Enter your email address',
    showPassword: 'Show Password',
    hidePassword: 'Hide Password',
    accountSecurity: 'Account Security',
    contactInformation: 'Contact Information',
    
    // Address Management
    addresses: 'Addresses',
    addAddress: 'Add Address',
    editAddress: 'Edit Address',
    deleteAddress: 'Delete Address',
    saveAddress: 'Save Address',
    saving: 'Saving...',
    cancel: 'Cancel',
    recipientName: 'Recipient Name',
    recipientPhone: 'Recipient Phone',
    streetAddress: 'Street Address',
    ward: 'Ward',
    district: 'District',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    address: 'Address',
    noAddresses: 'No Addresses Found',
    noAddressesDesc: 'You haven\'t added any addresses yet. Add your first address to make checkout easier!',
    
    // Product Filters and Listing
    allProductsPage: 'All Products',
    discoverOurCollection: 'Discover our diverse jewelry collection',
    productsInCategory: 'Products in category',
    searchResults: 'Search results',
    found: 'Found',
    allProductsLowercase: 'products',
    searchProductsPlaceholder: 'Search',
    searchProducts: 'Search products...',
    category: 'Category',
    allCategories: 'All Categories',
    priceRange: 'Price Range',
    sortBy: 'Sort By',
    sortByName: 'Name',
    sortByPrice: 'Price',
    sortByNewest: 'Newest',
    filterProducts: 'Filter Products',
    clearFilters: 'Clear Filters',
    applyFilters: 'Apply Filters',
    noProductsFound: 'No products found',
    noProductsMessage: 'Currently no products match your search criteria.',
    viewAllProducts: 'View all products',
    showing: 'Showing',
    viewDetailsPage: 'View details',
    allPrices: 'All Prices',
    under500k: 'Under 500K',
    above5m: 'Above 5M',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    outOf: 'out of',
    adjustFiltersMessage: 'Please try adjusting the filters to find suitable products',

    // Contact Page
    contactUsPage: 'Contact Us',
    contactSubtitle: 'Get in touch with us for any inquiries or custom jewelry requests',
    getInTouch: 'Get In Touch',
    contactDescription: 'We would love to hear from you. Send us a message and we will respond as soon as possible.',
    owner: 'Owner & Founder',
    businessHours: 'Business Hours',
    daily: 'Daily',
    sendMessage: 'Send Message',
    formDescription: 'Fill out the form below and we will get back to you within 24 hours.',
    fullName: 'Full Name',
    enterName: 'Enter your full name',
    enterEmail: 'Enter your email address',
    subject: 'Subject',
    enterSubject: 'Enter message subject',
    message: 'Message',
    enterMessage: 'Enter your message here...',
    sending: 'Sending...',
    messageSent: 'Thank you! Your message has been sent successfully.',
    messageError: 'Sorry, there was an error sending your message. Please try again.',
    findUs: 'Find Us',
    mapComing: 'Interactive map coming soon',
    linkedinProfile: 'LinkedIn Profile',
    getDirections: 'Get Directions',

    // About Page
    aboutUs: 'About Us',
    aboutSubtitle: 'Discover the story behind PANJ Jewelry and our passion for exquisite craftsmanship',
    ourStory: 'Our Story',
    storyParagraph1: 'PANJ Jewelry was born from a passion for creating beautiful, timeless pieces that celebrate life\'s most precious moments. Founded by Trương Hoàng Long, our brand represents the perfect fusion of traditional craftsmanship and contemporary design.',
    storyParagraph2: 'Every piece in our collection is carefully curated and crafted with attention to detail, using only the finest materials. We believe that jewelry is not just an accessory, but a way to express your unique story and personality.',
    storyParagraph3: 'From elegant necklaces to stunning rings, each piece is designed to be treasured for generations. Our commitment to quality and customer satisfaction has made us a trusted name in the jewelry industry.',
    meetFounder: 'Meet Our Founder',
    founderTitle: 'Jewelry Designer & Entrepreneur',
    founderDescription: 'With a background in design and a passion for creating beautiful jewelry, Trương Hoàng Long established PANJ Jewelry to bring unique, high-quality pieces to jewelry lovers everywhere.',
    ourValues: 'Our Values',
    qualityTitle: 'Premium Quality',
    qualityDescription: 'We use only the finest materials and gemstones to ensure each piece meets our high standards.',
    craftsmanshipTitle: 'Expert Craftsmanship',
    craftsmanshipDescription: 'Our skilled artisans bring years of experience to every piece they create.',
    passionTitle: 'Passion for Beauty',
    passionDescription: 'We are driven by our love for creating beautiful, meaningful jewelry.',
    customerTitle: 'Customer Focus',
    customerDescription: 'Your satisfaction is our priority, from design to delivery and beyond.',
    ourMission: 'Our Mission',
    missionStatement: 'To create exceptional jewelry that captures the beauty of life\'s most precious moments, while providing an outstanding customer experience that exceeds expectations.',
    goal1: 'Create timeless, elegant jewelry designs',
    goal2: 'Use only premium materials and gemstones',
    goal3: 'Provide exceptional customer service',
    goal4: 'Build lasting relationships with our customers',
    byNumbers: 'PANJ by the Numbers',
    happyCustomers: 'Happy Customers',
    jewelryPieces: 'Jewelry Pieces Created',
    uniqueDesigns: 'Unique Designs',
    yearsExperience: 'Years of Experience',
    joinJourney: 'Join Our Journey',
    joinDescription: 'Become part of the PANJ family and discover jewelry that tells your story.',
    exploreCollection: 'Explore Collection',
  },
  vi: {
    // Navigation
    home: 'Trang Chủ',
    products: 'Sản Phẩm',
    about: 'Về Chúng Tôi',
    contact: 'Liên Hệ',
    login: 'Đăng Nhập',
    register: 'Đăng Ký',
    logout: 'Đăng Xuất',
    cart: 'Giỏ Hàng',
    myOrders: 'Đơn Hàng',
    myProfile: 'Thông Tin Cá Nhân',
    
    // Hero Section
    heroTitle: 'PANJ',
    heroSubtitle: 'Khám phá vẻ đẹp vượt thời gian với bộ sưu tập trang sức cao cấp được chế tác thủ công',
    heroButton: 'Khám Phá Bộ Sưu Tập',
    
    // Products
    newCollection: 'Bộ Sưu Tập Mới',
    newCollectionDesc: 'Những thiết kế độc đáo mới nhất, được chế tác bằng nghệ thuật và đam mê',
    hotTrends: 'Xu Hướng Hot Nhất',
    hotTrendsDesc: 'Những món trang sức được yêu thích và lựa chọn nhiều nhất bởi khách hàng',
    viewDetails: 'Xem Chi Tiết',
    hotTrend: '🔥 Hot Trend',
    luxuryJewelry: 'Trang sức cao cấp từ PANJ',
    bestSeller: 'Sản phẩm bán chạy nhất',
    noNewProducts: 'Không có sản phẩm mới',
    noHotProducts: 'Không có sản phẩm hot',
    
    // Products Page
    allProducts: 'Tất Cả Sản Phẩm',
    productsInCategory: 'Sản phẩm trong danh mục',
    noProductsFound: 'Không tìm thấy sản phẩm',
    noProductsInCategory: 'Không có sản phẩm trong danh mục này',
    sortBy: 'Sắp xếp theo',
    sortByName: 'Tên',
    sortByPrice: 'Giá',
    sortByNewest: 'Mới nhất',
    sortByPopular: 'Phổ biến',
    priceRange: 'Khoảng Giá',
    allPrices: 'Tất Cả Giá',
    filterBy: 'Lọc theo',
    category: 'Danh Mục',
    color: 'Màu Sắc',
    material: 'Chất Liệu',
    clearFilters: 'Xóa Bộ Lọc',
    showingResults: 'Hiển thị',
    of: 'của',
    results: 'kết quả',
    
    // About Page
    aboutUs: 'Về Chúng Tôi',
    aboutPanj: 'Về PANJ',
    aboutTitle: 'Tạo Nên Vẻ Đẹp Vượt Thời Gian Từ 2020',
    aboutDescription: 'PANJ là thương hiệu trang sức cao cấp hàng đầu Việt Nam.',
    ourStory: 'Câu Chuyện Của Chúng Tôi',
    ourStoryText: 'Được thành lập với niềm đam mê về nghề thủ công đặc biệt.',
    ourMission: 'Sứ Mệnh',
    ourMissionText: 'Mang đến cho bạn những món trang sức tôn vinh những khoảnh khắc quý giá.',
    ourVision: 'Tầm Nhìn',
    ourVisionText: 'Trở thành thương hiệu trang sức cao cấp đáng tin cậy nhất thế giới.',
    
    // Contact Page
    contactUs: 'Liên Hệ',
    getInTouch: 'Liên Hệ Với Chúng Tôi',
    contactDescription: 'Chúng tôi rất muốn nghe từ bạn.',
    yourName: 'Họ Tên',
    yourEmail: 'Email',
    subject: 'Tiêu Đề',
    sendMessage: 'Gửi Tin Nhắn',
    sending: 'Đang gửi...',
    messageSent: 'Tin nhắn đã được gửi thành công!',
    messageError: 'Lỗi khi gửi tin nhắn.',
    contactInfo: 'Thông Tin Liên Hệ',
    address: 'Địa Chỉ',
    openingHours: 'Giờ Mở Cửa',
    
    // Social Login
    continueWithGoogle: 'Tiếp tục với Google',
    continueWithFacebook: 'Tiếp tục với Facebook',
    signUpWithGoogle: 'Đăng ký với Google',
    signUpWithFacebook: 'Đăng ký với Facebook',
    socialLoginError: 'Đăng nhập mạng xã hội thất bại.',
    noNewProducts: 'Hiện tại chưa có sản phẩm mới',
    noHotProducts: 'Hiện tại chưa có sản phẩm hot',
    
    // Features
    whyChoosePanj: 'Tại Sao Chọn PANJ',
    whyChoosePanjDesc: 'Chúng tôi cam kết mang đến cho bạn những trải nghiệm tuyệt vời nhất',
    qualityTitle: 'Chất Lượng Vượt Trội',
    qualityDesc: 'Sản phẩm được chế tác từ nguyên liệu cao cấp nhất thế giới với tiêu chuẩn quốc tế',
    designTitle: 'Thiết Kế Độc Quyền',
    designDesc: 'Mỗi món trang sức đều mang trong mình câu chuyện riêng và thiết kế không trùng lặp',
    serviceTitle: 'Dịch Vụ Hoàn Hảo',
    serviceDesc: 'Bảo hành trọn đời, miễn phí vận chuyển và dịch vụ chăm sóc khách hàng 24/7',
    
    // Authentication
    loginSubtitle: 'Đăng nhập vào tài khoản PANJ của bạn',
    username: 'Tên đăng nhập',
    password: 'Mật khẩu',
    usernamePlaceholder: 'Nhập tên đăng nhập',
    passwordPlaceholder: 'Nhập mật khẩu',
    rememberMe: 'Ghi nhớ đăng nhập',
    forgotPassword: 'Quên mật khẩu?',
    loggingIn: 'Đang đăng nhập...',
    or: 'hoặc',
    continueWithGoogle: 'Tiếp tục với Google',
    continueWithFacebook: 'Tiếp tục với Facebook',
    noAccount: 'Chưa có tài khoản?',
    signUp: 'Đăng ký',
    pleaseInputCredentials: 'Vui lòng nhập tên đăng nhập và mật khẩu',
    loginFailed: 'Đăng nhập thất bại',
    loginError: 'Có lỗi xảy ra trong quá trình đăng nhập',
    incorrectCredentials: 'Tên đăng nhập hoặc mật khẩu không chính xác. Vui lòng kiểm tra lại thông tin và thử lại.',
    accountDeactivated: 'Tài khoản của bạn chưa được kích hoạt. Vui lòng kiểm tra email để kích hoạt tài khoản.',
    
    // Sign Up
    createAccount: 'Tạo Tài Khoản',
    signupSubtitle: 'Tham gia PANJ và khám phá trang sức cao cấp',
    fullName: 'Họ và tên',
    email: 'Email',
    phone: 'Số điện thoại',
    confirmPassword: 'Xác nhận mật khẩu',
    fullNamePlaceholder: 'Nhập họ và tên',
    emailPlaceholder: 'Nhập địa chỉ email',
    phonePlaceholder: 'Nhập số điện thoại',
    confirmPasswordPlaceholder: 'Xác nhận mật khẩu',
    agreeToTerms: 'Tôi đồng ý với',
    termsAndConditions: 'Điều khoản và Điều kiện',
    subscribeNewsletter: 'Đăng ký nhận bản tin để nhận ưu đãi độc quyền',
    creatingAccount: 'Đang tạo tài khoản...',
    signUpWithGoogle: 'Đăng ký với Google',
    signUpWithFacebook: 'Đăng ký với Facebook',
    alreadyHaveAccount: 'Đã có tài khoản?',
    signIn: 'Đăng nhập',
    passwordMismatch: 'Mật khẩu không khớp',
    mustAgreeToTerms: 'Bạn phải đồng ý với điều khoản và điều kiện',
    signupSuccess: 'Tạo tài khoản thành công! Vui lòng kiểm tra email để kích hoạt tài khoản.',
    signupFailed: 'Tạo tài khoản thất bại',
    signupError: 'Có lỗi xảy ra trong quá trình tạo tài khoản',
    activationSent: 'Đã gửi email kích hoạt thành công',
    usernameExists: 'Tên đăng nhập đã tồn tại',
    emailExists: 'Email đã tồn tại',
    
    // Account Activation
    accountActivation: 'Kích Hoạt Tài Khoản',
    activatingAccount: 'Đang kích hoạt tài khoản của bạn...',
    activationSuccess: 'Tài khoản của bạn đã được kích hoạt thành công!',
    activationFailed: 'Kích hoạt tài khoản thất bại',
    activationError: 'Có lỗi xảy ra trong quá trình kích hoạt',
    redirectingToLogin: 'Đang chuyển đến trang đăng nhập...',
    activationExpired: 'Liên kết kích hoạt đã hết hạn',
    alreadyActivated: 'Tài khoản đã được kích hoạt',
    emailConfirmationMessage: 'Hãy kiểm tra email của bạn và nhấp vào liên kết kích hoạt để xác nhận tài khoản trước khi đăng nhập.',
    goToLogin: 'Đi đến Đăng Nhập',
    signUpAgain: 'Đăng Ký Lại',
    
    // Notifications
    success: 'Thành Công',
    error: 'Lỗi',
    warning: 'Cảnh Báo', 
    info: 'Thông Tin',
    networkError: 'Lỗi Mạng',
    checkConnection: 'Vui lòng kiểm tra kết nối internet và thử lại',
    
    // Footer
    footerDesc: 'Thương hiệu trang sức cao cấp hàng đầu Việt Nam. Chúng tôi tạo ra những món trang sức tinh xảo, mang đến vẻ đẹp vượt thời gian cho phái đẹp.',
    productsMenu: 'Sản Phẩm',
    allProducts: 'Tất Cả Sản Phẩm',
    rings: 'Nhẫn',
    necklaces: 'Dây Chuyền',
    bracelets: 'Vòng Tay',
    earrings: 'Hoa Tai',
    customerSupport: 'Hỗ Trợ Khách Hàng',
    contactUs: 'Liên Hệ',
    shipping: 'Giao Hàng',
    returns: 'Đổi Trả',
    warranty: 'Bảo Hành',
    careGuide: 'Hướng Dẫn Bảo Quản',
    contactInfo: 'Liên Hệ',
    address: '📍 Binh Thanh, Ho Chi Minh City',
    contactEmail: '✉️ truonghoanglong1802@gmail.com',
    linkedin: '💼 LinkedIn Profile',
    hours: '🕒 8:00 - 22:00 (Hàng ngày)',
    copyright: '© 2025 PANJ Jewelry. Tất cả quyền được bảo lưu.',
    privacyPolicy: 'Chính Sách Bảo Mật',
    termsOfUse: 'Điều Khoản Sử Dụng',
    sitemap: 'Sơ Đồ Trang Web',
    
    // Currency
    currency: 'VNĐ',
    
    // Common
    loading: 'Đang tải...',
    search: 'Tìm kiếm sản phẩm...',
    welcome: 'Xin chào',

    // Product Detail Page
    reviews: 'Đánh Giá',
    taxIncluded: 'Đã bao gồm thuế',
    freeShipping: 'Miễn phí vận chuyển',
    size: 'Kích Thước',
    sizeGuide: 'Hướng Dẫn Kích Thước',
    quantity: 'Số Lượng',
    adding: 'Đang thêm...',
    addToCart: 'Thêm Vào Giỏ',
    addToWishlist: 'Thêm Vào Yêu Thích',
    addedToCart: 'Đã thêm vào giỏ hàng thành công!',
    pleaseSelectSizeAndColor: 'Vui lòng chọn kích thước và màu sắc',
    authenticGuarantee: 'Bảo hành chính hãng',
    freeShippingOver: 'Miễn phí ship đơn > 2.000.000đ',
    returnPolicy: 'Đổi trả trong 30 ngày',
    lifetimeWarranty: 'Bảo hành trọn đời',
    share: 'Chia Sẻ',
    needHelp: 'Cần Hỗ Trợ?',
    description: 'Mô Tả',
    specifications: 'Thông Số',
    careInstructions: 'Hướng Dẫn Bảo Quản',
    productDescription: 'Mô Tả Sản Phẩm',
    luxuryJewelryDescription: 'Nghệ thuật chế tác tinh xảo kết hợp với vẻ đẹp vượt thời gian. Sản phẩm được làm thủ công tỉ mỉ bằng những nguyên liệu cao cấp nhất, đảm bảo cả vẻ đẹp lẫn độ bền. Hoàn hảo cho những dịp đặc biệt hoặc sang trọng hàng ngày.',
    handcraftedExcellence: 'Chế tác thủ công xuất sắc',
    premiumMaterials: 'Chỉ sử dụng nguyên liệu cao cấp',
    timelessDesign: 'Thiết kế vượt thời gian',
    perfectGift: 'Hoàn hảo để làm quà',
    material: 'Chất Liệu',
    plating: 'Lớp Mạ',
    stones: 'Đá Quý',
    weight: 'Trọng Lượng',
    dimensions: 'Kích Thước',
    origin: 'Xuất Xứ',
    cleaning: 'Vệ Sinh',
    storage: 'Bảo Quản',
    avoid: 'Tránh',
    cleaningInstructions: 'Làm sạch nhẹ nhàng bằng khăn mềm và xà phòng dịu. Rửa sạch bằng nước và lau khô kỹ.',
    storageInstructions: 'Bảo quản trong hộp gốc hoặc túi mềm để tránh trầy xước và oxy hóa.',
    avoidInstructions: 'Tránh tiếp xúc với nước hoa, kem dưỡng và hóa chất mạnh.',
    addedToCart: 'Đã thêm sản phẩm vào giỏ hàng!',
    close: 'Đóng',
    
    // Cart Page  
    emptyCart: 'Giỏ hàng trống',
    emptyCartMessage: 'Có vẻ như bạn chưa thêm gì vào giỏ hàng.',
    continueShopping: 'Tiếp tục mua sắm',
    itemsInCart: 'Sản phẩm trong giỏ',
    orderSummary: 'Tóm tắt đơn hàng',
    subtotal: 'Tạm tính',
    tax: 'Thuế',
    total: 'Tổng cộng',
    free: 'Miễn phí',
    proceedToCheckout: 'Tiến hành thanh toán',
    
    // Payment
    payment: 'Thanh Toán',
    paymentDetails: 'Thông Tin Thanh Toán',
    cardNumber: 'Số Thẻ',
    expiryDate: 'Ngày Hết Hạn',
    cvv: 'CVV',
    cardholderName: 'Tên Chủ Thẻ',
    payNow: 'Thanh Toán Ngay',
    processing: 'Đang xử lý...',
    backToCart: 'Quay Lại Giỏ Hàng',
    testPayment: 'Thanh Toán Thử',
    securePayment: 'Thanh Toán An Toàn',
    testMode: 'Chế Độ Thử',
    enterCardNumber: 'Nhập số thẻ của bạn',
    enterExpiryDate: 'MM/YY',
    enterCvv: 'CVV',
    enterCardholderName: 'Nhập tên chủ thẻ',
    paymentSuccessful: 'Thanh Toán Thành Công!',
    paymentFailed: 'Thanh Toán Thất Bại',
    orderPlaced: 'Đơn hàng của bạn đã được đặt thành công. Cảm ơn bạn đã mua hàng!',
    orderTotal: 'Tổng Đơn Hàng',
    paymentMethod: 'Phương Thức Thanh Toán',
    status: 'Trạng Thái',
    confirmed: 'Đã Xác Nhận',
    creditCard: 'Thẻ Tín Dụng',
    redirectingHome: 'Đang chuyển về trang chủ...',
    tryAgain: 'Thử Lại',
    backToCart: 'Về Giỏ Hàng',
    
    // Payment Process
    shippingInfo: 'Thông Tin Giao Hàng',
    shippingInfoDesc: 'Vui lòng cung cấp địa chỉ giao hàng và tùy chọn giao hàng',
    paymentInfo: 'Thông Tin Thanh Toán',
    orderConfirmation: 'Xác Nhận Đơn Hàng',
    recipientName: 'Tên Người Nhận',
    recipientPhone: 'Số Điện Thoại Người Nhận',
    streetAddress: 'Địa Chỉ Đường',
    ward: 'Phường/Xã',
    district: 'Quận/Huyện',
    city: 'Thành Phố/Tỉnh',
    country: 'Quốc Gia',
    postalCode: 'Mã Bưu Chính',
    deliveryMethod: 'Phương Thức Giao Hàng',
    standard: 'Tiêu Chuẩn',
    express: 'Nhanh',
    orderNotes: 'Ghi Chú Đơn Hàng',
    orderNotesPlaceholder: 'Bất kỳ hướng dẫn đặc biệt nào cho đơn hàng của bạn...',
    optional: 'Tùy Chọn',
    next: 'Tiếp Theo',
    useCustomerAddress: 'Sử Dụng Địa Chỉ Khách Hàng',
    edit: 'Chỉnh Sửa',
    editAddress: 'Chỉnh Sửa Địa Chỉ',
    recipientInfo: 'Thông Tin Người Nhận',
    addressDetails: 'Chi Tiết Địa Chỉ',
    deliveryOptions: 'Tùy Chọn Giao Hàng',
    additionalInfo: 'Thông Tin Bổ Sung',
    standardDeliveryDesc: 'Giao hàng trong 5-7 ngày làm việc',
    expressDeliveryDesc: 'Giao hàng trong 2-3 ngày làm việc',
    
    // My Orders
    myOrders: 'Đơn Hàng Của Tôi',
    orderHistory: 'Lịch Sử Đơn Hàng',
    orderId: 'Mã Đơn Hàng',
    orderDate: 'Ngày Đặt Hàng',
    viewDetails: 'Xem Chi Tiết',
    orderDetails: 'Chi Tiết Đơn Hàng',
    product: 'Sản Phẩm',
    quantity: 'Số Lượng',
    amount: 'Thành Tiền',
    subtotal: 'Tạm Tính',
    noOrders: 'Không Có Đơn Hàng',
    noOrdersMessage: 'Bạn chưa đặt đơn hàng nào. Hãy bắt đầu mua sắm để xem đơn hàng tại đây!',
    continueShopping: 'Tiếp Tục Mua Sắm',
    backToOrders: 'Về Danh Sách Đơn Hàng',
    orderSummary: 'Tóm Tắt Đơn Hàng',
    
    // My Profile
    myProfile: 'Hồ Sơ Của Tôi',
    personalInformation: 'Thông Tin Cá Nhân',
    updateProfile: 'Cập Nhật Hồ Sơ',
    updating: 'Đang cập nhật...',
    profileUpdated: 'Cập nhật hồ sơ thành công!',
    profileUpdateError: 'Cập nhật hồ sơ thất bại',
    enterUsername: 'Nhập tên đăng nhập',
    enterPassword: 'Nhập mật khẩu',
    enterName: 'Nhập họ và tên',
    enterPhone: 'Nhập số điện thoại',
    enterEmail: 'Nhập địa chỉ email',
    showPassword: 'Hiển Thị Mật Khẩu',
    hidePassword: 'Ẩn Mật Khẩu',
    accountSecurity: 'Bảo Mật Tài Khoản',
    contactInformation: 'Thông Tin Liên Hệ',
    
    // Address Management
    addresses: 'Địa Chỉ',
    addAddress: 'Thêm Địa Chỉ',
    editAddress: 'Chỉnh Sửa Địa Chỉ',
    deleteAddress: 'Xóa Địa Chỉ',
    saveAddress: 'Lưu Địa Chỉ',
    saving: 'Đang lưu...',
    cancel: 'Hủy',
    recipientName: 'Tên Người Nhận',
    recipientPhone: 'Số Điện Thoại',
    streetAddress: 'Địa Chỉ',
    ward: 'Phường/Xã',
    district: 'Quận/Huyện',
    city: 'Thành Phố/Tỉnh',
    postalCode: 'Mã Bưu Chính',
    country: 'Quốc Gia',
    address: 'Địa Chỉ',
    noAddresses: 'Chưa Có Địa Chỉ',
    noAddressesDesc: 'Bạn chưa thêm địa chỉ nào. Hãy thêm địa chỉ đầu tiên để thanh toán dễ dàng hơn!',
    
    // Product Filters and Listing  
    allProductsPage: 'Tất Cả Sản Phẩm',
    discoverOurCollection: 'Khám phá bộ sưu tập trang sức đa dạng của chúng tôi',
    productsInCategory: 'Sản phẩm thuộc danh mục',
    searchResults: 'Kết quả tìm kiếm',
    found: 'Tìm thấy',
    allProductsLowercase: 'sản phẩm',
    searchProductsPlaceholder: 'Tìm Kiếm',
    searchProducts: 'Tìm kiếm sản phẩm...',
    category: 'Danh Mục',
    allCategories: 'Tất Cả Danh Mục',
    priceRange: 'Khoảng Giá',
    sortBy: 'Sắp Xếp Theo',
    sortByName: 'Tên',
    sortByPrice: 'Giá',
    sortByNewest: 'Mới Nhất',
    filterProducts: 'Lọc Sản Phẩm',
    clearFilters: 'Xóa Bộ Lọc',
    applyFilters: 'Áp Dụng Bộ Lọc',
    noProductsFound: 'Không tìm thấy sản phẩm',
    noProductsMessage: 'Hiện tại không có sản phẩm nào phù hợp với tiêu chí tìm kiếm.',
    viewAllProducts: 'Xem tất cả sản phẩm',
    showing: 'Hiển thị',
    viewDetailsPage: 'Xem chi tiết',
    allPrices: 'Tất Cả Mức Giá',
    under500k: 'Dưới 500K',
    above5m: 'Trên 5M',
    priceLowToHigh: 'Giá: Thấp đến Cao',
    priceHighToLow: 'Giá: Cao đến Thấp',
    outOf: 'trong số',
    adjustFiltersMessage: 'Vui lòng thử điều chỉnh bộ lọc để tìm sản phẩm phù hợp',

    // Contact Page
    contactUsPage: 'Liên Hệ',
    contactSubtitle: 'Liên hệ với chúng tôi cho bất kỳ thắc mắc hoặc yêu cầu trang sức tùy chỉnh nào',
    getInTouch: 'Liên Hệ Ngay',
    contactDescription: 'Chúng tôi rất muốn được nghe từ bạn. Gửi tin nhắn cho chúng tôi và chúng tôi sẽ phản hồi sớm nhất có thể.',
    owner: 'Chủ Sở Hữu & Người Sáng Lập',
    businessHours: 'Giờ Làm Việc',
    daily: 'Hàng Ngày',
    sendMessage: 'Gửi Tin Nhắn',
    formDescription: 'Điền vào biểu mẫu bên dưới và chúng tôi sẽ liên hệ lại với bạn trong vòng 24 giờ.',
    fullName: 'Họ Và Tên',
    enterName: 'Nhập họ và tên của bạn',
    enterEmail: 'Nhập địa chỉ email của bạn',
    subject: 'Chủ Đề',
    enterSubject: 'Nhập chủ đề tin nhắn',
    message: 'Tin Nhắn',
    enterMessage: 'Nhập tin nhắn của bạn tại đây...',
    sending: 'Đang Gửi...',
    messageSent: 'Cảm ơn bạn! Tin nhắn của bạn đã được gửi thành công.',
    messageError: 'Xin lỗi, đã có lỗi khi gửi tin nhắn của bạn. Vui lòng thử lại.',
    findUs: 'Tìm Chúng Tôi',
    mapComing: 'Bản đồ tương tác sẽ có sớm',
    linkedinProfile: 'Hồ Sơ LinkedIn',
    getDirections: 'Chỉ Đường',

    // About Page
    aboutUs: 'Về Chúng Tôi',
    aboutSubtitle: 'Khám phá câu chuyện đằng sau PANJ Jewelry và niềm đam mê tạo ra những tác phẩm tinh xảo',
    ourStory: 'Câu Chuyện Của Chúng Tôi',
    storyParagraph1: 'PANJ Jewelry ra đời từ niềm đam mê tạo ra những món trang sức đẹp, vượt thời gian để tôn vinh những khoảnh khắc quý giá nhất trong cuộc sống. Được thành lập bởi Trương Hoàng Long, thương hiệu của chúng tôi đại diện cho sự kết hợp hoàn hảo giữa nghề thủ công truyền thống và thiết kế đương đại.',
    storyParagraph2: 'Mỗi món đồ trong bộ sưu tập của chúng tôi đều được tuyển chọn và chế tác cẩn thận với sự chú ý đến từng chi tiết, chỉ sử dụng những vật liệu tốt nhất. Chúng tôi tin rằng trang sức không chỉ là phụ kiện, mà còn là cách để thể hiện câu chuyện và cá tính độc đáo của bạn.',
    storyParagraph3: 'Từ những chiếc vòng cổ thanh lịch đến những chiếc nhẫn tuyệt đẹp, mỗi món đồ đều được thiết kế để trở thành báu vật cho nhiều thế hệ. Cam kết của chúng tôi về chất lượng và sự hài lòng của khách hàng đã khiến chúng tôi trở thành một cái tên đáng tin cậy trong ngành trang sức.',
    meetFounder: 'Gặp Gỡ Người Sáng Lập',
    founderTitle: 'Nhà Thiết Kế Trang Sức & Doanh Nhân',
    founderDescription: 'Với nền tảng thiết kế và niềm đam mê tạo ra những món trang sức đẹp, Trương Hoàng Long đã thành lập PANJ Jewelry để mang đến những sản phẩm độc đáo, chất lượng cao cho những người yêu trang sức trên khắp mọi nơi.',
    ourValues: 'Giá Trị Của Chúng Tôi',
    qualityTitle: 'Chất Lượng Cao Cấp',
    qualityDescription: 'Chúng tôi chỉ sử dụng những vật liệu và đá quý tốt nhất để đảm bảo mỗi sản phẩm đáp ứng tiêu chuẩn cao của chúng tôi.',
    craftsmanshipTitle: 'Nghề Thủ Công Chuyên Nghiệp',
    craftsmanshipDescription: 'Các nghệ nhân lành nghề của chúng tôi mang nhiều năm kinh nghiệm vào từng sản phẩm họ tạo ra.',
    passionTitle: 'Đam Mê Vẻ Đẹp',
    passionDescription: 'Chúng tôi được thúc đẩy bởi tình yêu tạo ra những món trang sức đẹp và ý nghĩa.',
    customerTitle: 'Tập Trung Vào Khách Hàng',
    customerDescription: 'Sự hài lòng của bạn là ưu tiên của chúng tôi, từ thiết kế đến giao hàng và hơn thế nữa.',
    ourMission: 'Sứ Mệnh Của Chúng Tôi',
    missionStatement: 'Tạo ra những món trang sức đặc biệt để nắm bắt vẻ đẹp của những khoảnh khắc quý giá nhất trong cuộc sống, đồng thời mang lại trải nghiệm khách hàng xuất sắc vượt quá mong đợi.',
    goal1: 'Tạo ra những thiết kế trang sức vượt thời gian, thanh lịch',
    goal2: 'Chỉ sử dụng vật liệu cao cấp và đá quý',
    goal3: 'Cung cấp dịch vụ khách hàng đặc biệt',
    goal4: 'Xây dựng mối quan hệ lâu dài với khách hàng',
    byNumbers: 'PANJ Qua Những Con Số',
    happyCustomers: 'Khách Hàng Hài Lòng',
    jewelryPieces: 'Món Trang Sức Được Tạo Ra',
    uniqueDesigns: 'Thiết Kế Độc Đáo',
    yearsExperience: 'Năm Kinh Nghiệm',
    joinJourney: 'Tham Gia Hành Trình Của Chúng Tôi',
    joinDescription: 'Trở thành một phần của gia đình PANJ và khám phá những món trang sức kể câu chuyện của bạn.',
    exploreCollection: 'Khám Phá Bộ Sưu Tập',
  },
  ja: {
    // Navigation
    home: 'ホーム',
    products: '製品',
    about: '私たちについて',
    contact: 'お問い合わせ',
    login: 'ログイン',
    register: '登録',
    logout: 'ログアウト',
    cart: 'カート',
    myOrders: '注文履歴',
    myProfile: 'プロフィール',
    
    // Hero Section
    heroTitle: 'PANJ',
    heroSubtitle: '手作りの高級ジュエリーコレクションで時代を超越した美しさを発見してください',
    heroButton: 'コレクションを見る',
    
    // Products
    newCollection: '新コレクション',
    newCollectionDesc: '芸術と情熱で作られた最新のユニークなデザイン',
    hotTrends: 'ホットトレンド',
    hotTrendsDesc: 'お客様に最も愛され選ばれたジュエリー',
    viewDetails: '詳細を見る',
    hotTrend: '🔥 ホットトレンド',
    luxuryJewelry: 'PANJの高級ジュエリー',
    bestSeller: 'ベストセラー商品',
    noNewProducts: '新しい製品はありません',
    noHotProducts: '人気商品はありません',
    
    // Products Page
    allProducts: '全ての商品',
    productsInCategory: 'カテゴリの商品',
    noProductsFound: '商品が見つかりません',
    noProductsInCategory: 'このカテゴリに商品がありません',
    sortBy: '並び替え',
    sortByName: '名前',
    sortByPrice: '価格',
    sortByNewest: '新着',
    sortByPopular: '人気',
    priceRange: '価格帯',
    allPrices: '全価格',
    filterBy: 'フィルター',
    category: 'カテゴリ',
    color: '色',
    material: '素材',
    clearFilters: 'フィルターをクリア',
    showingResults: '表示中',
    of: '/',
    results: '件',
    // About Page
    aboutUs: '私たちについて',
    aboutSubtitle: 'PANJジュエリーの背景にある物語と、精巧な職人技への情熱をご覧ください',
    aboutPanj: 'PANJについて',
    aboutTitle: '2020年から時代を超越した美しさを創造',
    aboutDescription: 'PANJはベトナムを代表する高級ジュエリーブランドです。',
    ourStory: '私たちの物語',
    storyParagraph1: 'PANJジュエリーは、人生の最も貴重な瞬間を祝う美しく時代を超越した作品を創造する情熱から生まれました。Trương Hoàng Longによって設立された私たちのブランドは、伝統的な職人技と現代的なデザインの完璧な融合を表しています。',
    storyParagraph2: 'コレクションの各作品は、細部への注意を払って慎重に厳選・制作され、最高の素材のみを使用しています。ジュエリーは単なるアクセサリーではなく、あなた独自の物語と個性を表現する方法だと信じています。',
    storyParagraph3: 'エレガントなネックレスから美しいリングまで、各作品は何世代にもわたって大切にされるようにデザインされています。品質とお客様満足への私たちのコミットメントにより、ジュエリー業界で信頼される名前となりました。',
    meetFounder: '創設者との出会い',
    founderTitle: 'ジュエリーデザイナー＆起業家',
    founderDescription: 'デザインの背景と美しいジュエリー創造への情熱を持つTrương Hoàng Longは、世界中のジュエリー愛好者にユニークで高品質な作品をお届けするためにPANJジュエリーを設立しました。',
    ourStoryText: '卓越した職人技への情熱で設立されました。',
    ourMission: '使命',
    ourMissionText: '人生の最も貴重な瞬間を祝うジュエリーをお届けします。',
    ourVision: 'ビジョン',
    ourVisionText: '世界で最も信頼され尊敬される高級ジュエリーブランドになること。',
    findUs: 'ロケーション',
    enterEmail: "メールアドレスを入力",
    enterSubject: "件名を入力",
    enterMessage: "メッセージを入力",
    // Values Section
    ourValues: '私たちの価値観',
    qualityTitle: '優れた品質',
    qualityDescription: '最高品質の素材と宝石のみを使用し、各作品が私たちの高い基準を満たすことを保証します。',
    craftsmanshipTitle: '専門的な職人技',
    craftsmanshipDescription: '熟練した職人が、作成するすべての作品に長年の経験をもたらします。',
    passionTitle: '美への情熱',
    passionDescription: '美しく意味のあるジュエリーを創造することへの愛に駆り立てられています。',
    customerTitle: 'お客様満足',
    customerDescription: 'お客様のニーズと期待を超えることが私たちの最優先事項です。',
    
    // Mission
    missionStatement: '人生の最も貴重な瞬間の美しさを捉える特別なジュエリーを創造し、期待を超える優れたお客様体験を提供すること。',
    goal1: '時代を超越したエレガントなジュエリーデザインを創造',
    goal2: '高級素材と宝石のみを使用',
    goal3: '特別なカスタマーサービスを提供',
    goal4: 'お客様との長期的な関係を構築',
    
    // Numbers
    byNumbers: 'PANJの実績',
    happyCustomers: '満足したお客様',
    jewelryPieces: '制作されたジュエリー',
    uniqueDesigns: 'ユニークデザイン',
    yearsExperience: '年の経験',
    
    // Join Journey
    joinJourney: '私たちの旅に参加',
    joinDescription: 'PANJファミリーの一員となり、あなたの物語を語るジュエリーを発見してください。',
    exploreCollection: 'コレクションを探索',
    
    // Contact Page
    contactUs: 'お問い合わせ',
    contactSubtitle: 'お気軽にお問い合わせください',
    getInTouch: 'ご連絡ください',
    contactDescription: 'お気軽にお問い合わせください。できるだけ早くご返答いたします。',
    yourName: 'お名前',
    yourEmail: 'メールアドレス',
    subject: '件名',
    message: 'メッセージ',
    sendMessage: 'メッセージを送信',
    sending: '送信中...',
    messageSent: 'メッセージが正常に送信されました！',
    messageError: 'メッセージの送信に失敗しました。もう一度お試しください。',
    contactInfo: '連絡先情報',
    address: '住所',
    openingHours: '営業時間',
    owner: 'オーナー',
    linkedinProfile: 'LinkedInプロフィールを見る',
    businessHours: '営業時間',
    daily: '毎日',
    fullName: '氏名',
    enterName: 'お名前を入力してください',
    formDescription: '以下のフォームにご記入ください。できるだけ早くご返答いたします。',

    // Social Login
    continueWithGoogle: 'Googleで続行',
    continueWithFacebook: 'Facebookで続行',
    signUpWithGoogle: 'Googleで登録',
    signUpWithFacebook: 'Facebookで登録',
    socialLoginError: 'ソーシャルログインに失敗しました。',
    noNewProducts: '新しい製品はありません',
    noHotProducts: '人気商品はありません',
    
    // Features
    whyChoosePanj: 'PANJを選ぶ理由',
    whyChoosePanjDesc: '最高の体験をお届けすることをお約束します',
    qualityTitle: '優れた品質',
    qualityDesc: '国際基準で世界最高の素材から作られた製品',
    designTitle: '独占デザイン',
    designDesc: 'それぞれのジュエリーは独自の物語と複製されないユニークなデザインを持っています',
    serviceTitle: '完璧なサービス',
    serviceDesc: '生涯保証、送料無料、24時間365日のカスタマーケア',
    
    // Authentication
    loginSubtitle: 'PANJアカウントにサインインしてください',
    username: 'ユーザー名',
    password: 'パスワード',
    usernamePlaceholder: 'ユーザー名を入力してください',
    passwordPlaceholder: 'パスワードを入力してください',
    rememberMe: 'ログイン情報を保存',
    forgotPassword: 'パスワードを忘れましたか？',
    loggingIn: 'サインイン中...',
    or: 'または',
    continueWithGoogle: 'Googleで続行',
    continueWithFacebook: 'Facebookで続行',
    noAccount: 'アカウントをお持ちでない方',
    signUp: 'サインアップ',
    pleaseInputCredentials: 'ユーザー名とパスワードを入力してください',
    loginFailed: 'ログインに失敗しました',
    loginError: 'ログイン中にエラーが発生しました',
    incorrectCredentials: 'ユーザー名またはパスワードが正しくありません。再度確認してください。',
    accountDeactivated: 'アカウントが有効化されていません。メールを確認してアカウントを有効化してください。',
    
    // Sign Up
    createAccount: 'アカウント作成',
    signupSubtitle: 'PANJに参加して高級ジュエリーを発見してください',
    fullName: 'フルネーム',
    email: 'メール',
    phone: '電話番号',
    confirmPassword: 'パスワード確認',
    fullNamePlaceholder: 'フルネームを入力してください',
    emailPlaceholder: 'メールアドレスを入力してください',
    phonePlaceholder: '電話番号を入力してください',
    confirmPasswordPlaceholder: 'パスワードを確認してください',
    agreeToTerms: '同意します',
    termsAndConditions: '利用規約',
    subscribeNewsletter: '限定オファーのニュースレターを購読する',
    creatingAccount: 'アカウント作成中...',
    signUpWithGoogle: 'Googleでサインアップ',
    signUpWithFacebook: 'Facebookでサインアップ',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
    signIn: 'サインイン',
    passwordMismatch: 'パスワードが一致しません',
    mustAgreeToTerms: '利用規約に同意する必要があります',
    signupSuccess: 'アカウントが正常に作成されました！アカウントを有効化するためにメールを確認してください。',
    signupFailed: 'アカウント作成に失敗しました',
    signupError: 'アカウント作成中にエラーが発生しました',
    activationSent: 'アクティベーションメールが正常に送信されました',
    usernameExists: 'ユーザー名は既に存在します',
    emailExists: 'メールは既に存在します',
    
    // Common
    loading: '読み込み中...',
    search: '製品を検索...',
    welcome: 'ようこそ',
    currency: 'JPY',
    
    // Cart
    emptyCart: 'カートは空です',
    emptyCartMessage: 'カートにまだ何も追加していないようです。',
    continueShopping: 'ショッピングを続ける',
    addToCart: 'カートに追加',
    quantity: '数量',
    total: '合計',
    subtotal: '小計',
    tax: '税金',
    
    // Product Detail
    addToWishlist: 'ウィッシュリストに追加',
    size: 'サイズ',
    description: '説明',
    specifications: '仕様',
    careInstructions: 'お手入れ方法',
    
    // Footer
    footerDesc: 'ベトナムを代表する高級ジュエリーブランド。女性に永遠の美しさをもたらす精巧なジュエリーを作成しています。',
    copyright: '© 2025 PANJ Jewelry. 全著作権所有。',
    
    // My Profile
    myProfile: 'マイプロフィール',
    personalInformation: '個人情報',
    updateProfile: 'プロフィール更新',
    
    // Address Management
    addresses: '住所',
    addAddress: '住所を追加',
    editAddress: '住所を編集',
    deleteAddress: '住所を削除',
    saveAddress: '住所を保存',
    recipientName: '受取人名',
    recipientPhone: '受取人電話番号',
    streetAddress: '住所',
    city: '市区町村',
    country: '国',
    postalCode: '郵便番号',
    
    // Payment
    payment: '支払い',
    paymentDetails: '支払い詳細',
    shippingInfo: '配送情報',
    paymentInfo: '支払い情報',
    orderConfirmation: '注文確認',
    deliveryMethod: '配送方法',
    standard: '標準',
    express: '速達',
    orderNotes: '注文メモ',
    next: '次へ',
    
    // Orders
    myOrders: '注文履歴',
    orderId: '注文ID',
    orderDate: '注文日',
    viewDetails: '詳細を見る',
    orderDetails: '注文詳細',
    
    // Others
    close: '閉じる',
    cancel: 'キャンセル',
    edit: '編集',
    save: '保存',
    delete: '削除',
    confirm: '確認',
    back: '戻る',
    success: '成功',
    error: 'エラー',
    warning: '警告',
    info: '情報'
  }
};

// Language Context
const LanguageContext = createContext();

// Language Provider
export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en'); // Default to English

  const t = (key) => {
    return translations[language][key] || key;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('panj_language', lang);
  };

  // Load language from localStorage on mount
  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('panj_language');
    if (savedLanguage && ['en', 'vi', 'ja'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const value = {
    language,
    setLanguage: changeLanguage,
    t,
    translations
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook to use language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// HOC to provide language context to class components
export const withLanguage = (WrappedComponent) => {
  return React.forwardRef((props, ref) => {
    const languageContext = useLanguage();
    
    return (
      <WrappedComponent
        ref={ref}
        {...props}
        language={languageContext.language}
        setLanguage={languageContext.setLanguage}
        t={languageContext.t}
        translations={languageContext.translations}
      />
    );
  });
};

export default LanguageContext;
